// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET
  balance = balance + $1,
  updated_at = now()
WHERE id = $2
  AND balance + $1 >= 0
RETURNING id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at
`

type AddAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const closeAccount = `-- name: CloseAccount :one
UPDATE accounts
SET
  status = 'closed',
  closed_at = now(),
  updated_at = now()
WHERE id = $1
  AND balance = 0
  AND status <> 'closed'
RETURNING id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at
`

func (q *Queries) CloseAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, closeAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  owner,
  balance,
  currency
) VALUES (
  $1, 0, $2
)
RETURNING id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at
`

type CreateAccountParams struct {
	Owner    string `json:"owner"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Owner, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getAccountByPublicID = `-- name: GetAccountByPublicID :one
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) GetAccountByPublicID(ctx context.Context, publicID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPublicID, publicID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getAccountByPublicIDForUpdate = `-- name: GetAccountByPublicIDForUpdate :one
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE public_id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountByPublicIDForUpdate(ctx context.Context, publicID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPublicIDForUpdate, publicID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOwnedAccountByPublicID = `-- name: GetOwnedAccountByPublicID :one
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE public_id = $1
  AND owner = $2
LIMIT 1
`

type GetOwnedAccountByPublicIDParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	Owner    string      `json:"owner"`
}

func (q *Queries) GetOwnedAccountByPublicID(ctx context.Context, arg GetOwnedAccountByPublicIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getOwnedAccountByPublicID, arg.PublicID, arg.Owner)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listAccount = `-- name: ListAccount :many
SELECT id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at FROM accounts
WHERE owner = $1
ORDER BY created_at, id
LIMIT $2
OFFSET $3
`

type ListAccountParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccount, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.PublicID,
			&i.Status,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountStatus = `-- name: SetAccountStatus :one
UPDATE accounts
SET
  status = $2,
  closed_at = NULL,
  updated_at = now()
WHERE id = $1
  AND $2 IN ('active', 'frozen')
RETURNING id, owner, balance, currency, created_at, public_id, status, updated_at, closed_at
`

type SetAccountStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.PublicID,
		&i.Status,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}
