// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beneficiary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBeneficiary = `-- name: CreateBeneficiary :one
INSERT INTO beneficiaries (
  owner,
  destination_account_id,
  nickname
) VALUES (
  $1, $2, $3
)
RETURNING id, owner, destination_account_id, nickname, created_at, updated_at
`

type CreateBeneficiaryParams struct {
	Owner                string `json:"owner"`
	DestinationAccountID int64  `json:"destination_account_id"`
	Nickname             string `json:"nickname"`
}

func (q *Queries) CreateBeneficiary(ctx context.Context, arg CreateBeneficiaryParams) (Beneficiary, error) {
	row := q.db.QueryRow(ctx, createBeneficiary, arg.Owner, arg.DestinationAccountID, arg.Nickname)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.DestinationAccountID,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOwnedBeneficiary = `-- name: DeleteOwnedBeneficiary :execrows
DELETE FROM beneficiaries
WHERE id = $1
  AND owner = $2
`

type DeleteOwnedBeneficiaryParams struct {
	BeneficiaryID pgtype.UUID `json:"beneficiary_id"`
	Owner         string      `json:"owner"`
}

func (q *Queries) DeleteOwnedBeneficiary(ctx context.Context, arg DeleteOwnedBeneficiaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnedBeneficiary, arg.BeneficiaryID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnedBeneficiaries = `-- name: ListOwnedBeneficiaries :many
SELECT
  beneficiary.id,
  beneficiary.nickname,
  account.account_number AS destination_account_number,
  account.currency,
  account.status AS destination_account_status,
  beneficiary.created_at,
  beneficiary.updated_at
FROM beneficiaries AS beneficiary
JOIN accounts AS account
  ON account.id = beneficiary.destination_account_id
WHERE beneficiary.owner = $1
ORDER BY beneficiary.created_at DESC, beneficiary.id DESC
LIMIT $2
OFFSET $3
`

type ListOwnedBeneficiariesParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListOwnedBeneficiariesRow struct {
	ID                       pgtype.UUID        `json:"id"`
	Nickname                 string             `json:"nickname"`
	DestinationAccountNumber string             `json:"destination_account_number"`
	Currency                 string             `json:"currency"`
	DestinationAccountStatus string             `json:"destination_account_status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOwnedBeneficiaries(ctx context.Context, arg ListOwnedBeneficiariesParams) ([]ListOwnedBeneficiariesRow, error) {
	rows, err := q.db.Query(ctx, listOwnedBeneficiaries, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedBeneficiariesRow{}
	for rows.Next() {
		var i ListOwnedBeneficiariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.DestinationAccountNumber,
			&i.Currency,
			&i.DestinationAccountStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnedBeneficiaryNickname = `-- name: UpdateOwnedBeneficiaryNickname :one
WITH updated AS (
  UPDATE beneficiaries
  SET
    nickname = $1,
    updated_at = now()
  WHERE beneficiaries.id = $2
    AND beneficiaries.owner = $3
  RETURNING id, owner, destination_account_id, nickname, created_at, updated_at
)
SELECT
  updated.id,
  updated.nickname,
  account.account_number AS destination_account_number,
  account.currency,
  account.status AS destination_account_status,
  updated.created_at,
  updated.updated_at
FROM updated
JOIN accounts AS account
  ON account.id = updated.destination_account_id
`

type UpdateOwnedBeneficiaryNicknameParams struct {
	Nickname      string      `json:"nickname"`
	BeneficiaryID pgtype.UUID `json:"beneficiary_id"`
	Owner         string      `json:"owner"`
}

type UpdateOwnedBeneficiaryNicknameRow struct {
	ID                       pgtype.UUID        `json:"id"`
	Nickname                 string             `json:"nickname"`
	DestinationAccountNumber string             `json:"destination_account_number"`
	Currency                 string             `json:"currency"`
	DestinationAccountStatus string             `json:"destination_account_status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOwnedBeneficiaryNickname(ctx context.Context, arg UpdateOwnedBeneficiaryNicknameParams) (UpdateOwnedBeneficiaryNicknameRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedBeneficiaryNickname, arg.Nickname, arg.BeneficiaryID, arg.Owner)
	var i UpdateOwnedBeneficiaryNicknameRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.DestinationAccountNumber,
		&i.Currency,
		&i.DestinationAccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
