// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_delivery_event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailDeliveryEvent = `-- name: CreateEmailDeliveryEvent :one
INSERT INTO email_delivery_events (
  webhook_id,
  email_job_id,
  provider_message_id,
  event_type,
  occurred_at,
  payload
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (webhook_id) DO NOTHING
RETURNING webhook_id, email_job_id, provider_message_id, event_type, occurred_at, received_at, payload
`

type CreateEmailDeliveryEventParams struct {
	WebhookID         string             `json:"webhook_id"`
	EmailJobID        pgtype.UUID        `json:"email_job_id"`
	ProviderMessageID string             `json:"provider_message_id"`
	EventType         string             `json:"event_type"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	Payload           []byte             `json:"payload"`
}

func (q *Queries) CreateEmailDeliveryEvent(ctx context.Context, arg CreateEmailDeliveryEventParams) (EmailDeliveryEvent, error) {
	row := q.db.QueryRow(ctx, createEmailDeliveryEvent,
		arg.WebhookID,
		arg.EmailJobID,
		arg.ProviderMessageID,
		arg.EventType,
		arg.OccurredAt,
		arg.Payload,
	)
	var i EmailDeliveryEvent
	err := row.Scan(
		&i.WebhookID,
		&i.EmailJobID,
		&i.ProviderMessageID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Payload,
	)
	return i, err
}

const getEmailDeliveryEvent = `-- name: GetEmailDeliveryEvent :one
SELECT webhook_id, email_job_id, provider_message_id, event_type, occurred_at, received_at, payload FROM email_delivery_events
WHERE webhook_id = $1
LIMIT 1
`

func (q *Queries) GetEmailDeliveryEvent(ctx context.Context, webhookID string) (EmailDeliveryEvent, error) {
	row := q.db.QueryRow(ctx, getEmailDeliveryEvent, webhookID)
	var i EmailDeliveryEvent
	err := row.Scan(
		&i.WebhookID,
		&i.EmailJobID,
		&i.ProviderMessageID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Payload,
	)
	return i, err
}

const listEmailDeliveryEventsByJob = `-- name: ListEmailDeliveryEventsByJob :many
SELECT webhook_id, email_job_id, provider_message_id, event_type, occurred_at, received_at, payload FROM email_delivery_events
WHERE email_job_id = $1
ORDER BY occurred_at DESC, received_at DESC
LIMIT $2
`

type ListEmailDeliveryEventsByJobParams struct {
	EmailJobID pgtype.UUID `json:"email_job_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListEmailDeliveryEventsByJob(ctx context.Context, arg ListEmailDeliveryEventsByJobParams) ([]EmailDeliveryEvent, error) {
	rows, err := q.db.Query(ctx, listEmailDeliveryEventsByJob, arg.EmailJobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDeliveryEvent{}
	for rows.Next() {
		var i EmailDeliveryEvent
		if err := rows.Scan(
			&i.WebhookID,
			&i.EmailJobID,
			&i.ProviderMessageID,
			&i.EventType,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
