// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_job.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailJob = `-- name: CreateEmailJob :one
INSERT INTO email_jobs (
  id,
  parent_job_id,
  job_type,
  username,
  recipient,
  payload,
  max_attempts
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

type CreateEmailJobParams struct {
	ID          pgtype.UUID `json:"id"`
	ParentJobID pgtype.UUID `json:"parent_job_id"`
	JobType     string      `json:"job_type"`
	Username    string      `json:"username"`
	Recipient   string      `json:"recipient"`
	Payload     []byte      `json:"payload"`
	MaxAttempts int32       `json:"max_attempts"`
}

func (q *Queries) CreateEmailJob(ctx context.Context, arg CreateEmailJobParams) (EmailJob, error) {
	row := q.db.QueryRow(ctx, createEmailJob,
		arg.ID,
		arg.ParentJobID,
		arg.JobType,
		arg.Username,
		arg.Recipient,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const deleteExpiredSentEmailJobs = `-- name: DeleteExpiredSentEmailJobs :execrows
DELETE FROM email_jobs
WHERE status = 'sent'
  AND sent_at < $1
`

func (q *Queries) DeleteExpiredSentEmailJobs(ctx context.Context, sentAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSentEmailJobs, sentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailJob = `-- name: GetEmailJob :one
SELECT id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at FROM email_jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEmailJob(ctx context.Context, id pgtype.UUID) (EmailJob, error) {
	row := q.db.QueryRow(ctx, getEmailJob, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const listDeadLetterEmailJobs = `-- name: ListDeadLetterEmailJobs :many
SELECT id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at FROM email_jobs
WHERE status = 'dead_letter'
ORDER BY dead_lettered_at DESC
LIMIT $1
`

func (q *Queries) ListDeadLetterEmailJobs(ctx context.Context, limit int32) ([]EmailJob, error) {
	rows, err := q.db.Query(ctx, listDeadLetterEmailJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailJob{}
	for rows.Next() {
		var i EmailJob
		if err := rows.Scan(
			&i.ID,
			&i.ParentJobID,
			&i.JobType,
			&i.Username,
			&i.Recipient,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.ProviderMessageID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QueuedAt,
			&i.ProcessingAt,
			&i.LastAttemptAt,
			&i.SentAt,
			&i.DeadLetteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailJobDeadLetter = `-- name: MarkEmailJobDeadLetter :one
UPDATE email_jobs
SET
  status = 'dead_letter',
  last_error = $2,
  dead_lettered_at = now(),
  updated_at = now()
WHERE id = $1
  AND status <> 'sent'
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

type MarkEmailJobDeadLetterParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEmailJobDeadLetter(ctx context.Context, arg MarkEmailJobDeadLetterParams) (EmailJob, error) {
	row := q.db.QueryRow(ctx, markEmailJobDeadLetter, arg.ID, arg.LastError)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const markEmailJobQueued = `-- name: MarkEmailJobQueued :one
UPDATE email_jobs
SET
  status = CASE WHEN status = 'pending' THEN 'queued' ELSE status END,
  queued_at = CASE WHEN status = 'pending' THEN now() ELSE queued_at END,
  updated_at = now()
WHERE id = $1
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

func (q *Queries) MarkEmailJobQueued(ctx context.Context, id pgtype.UUID) (EmailJob, error) {
	row := q.db.QueryRow(ctx, markEmailJobQueued, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const markEmailJobRetrying = `-- name: MarkEmailJobRetrying :one
UPDATE email_jobs
SET
  status = 'retrying',
  last_error = $2,
  updated_at = now()
WHERE id = $1
  AND status <> 'sent'
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

type MarkEmailJobRetryingParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEmailJobRetrying(ctx context.Context, arg MarkEmailJobRetryingParams) (EmailJob, error) {
	row := q.db.QueryRow(ctx, markEmailJobRetrying, arg.ID, arg.LastError)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const markEmailJobSent = `-- name: MarkEmailJobSent :one
UPDATE email_jobs
SET
  status = 'sent',
  provider_message_id = $2,
  last_error = NULL,
  sent_at = now(),
  updated_at = now()
WHERE id = $1
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

type MarkEmailJobSentParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

func (q *Queries) MarkEmailJobSent(ctx context.Context, arg MarkEmailJobSentParams) (EmailJob, error) {
	row := q.db.QueryRow(ctx, markEmailJobSent, arg.ID, arg.ProviderMessageID)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}

const startEmailJobAttempt = `-- name: StartEmailJobAttempt :one
UPDATE email_jobs
SET
  status = 'processing',
  attempt_count = attempt_count + 1,
  processing_at = now(),
  last_attempt_at = now(),
  updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'queued', 'processing', 'retrying')
RETURNING id, parent_job_id, job_type, username, recipient, payload, status, attempt_count, max_attempts, provider_message_id, last_error, created_at, updated_at, queued_at, processing_at, last_attempt_at, sent_at, dead_lettered_at
`

func (q *Queries) StartEmailJobAttempt(ctx context.Context, id pgtype.UUID) (EmailJob, error) {
	row := q.db.QueryRow(ctx, startEmailJobAttempt, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.ParentJobID,
		&i.JobType,
		&i.Username,
		&i.Recipient,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ProviderMessageID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.DeadLetteredAt,
	)
	return i, err
}
