// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET
  transaction_id = $4,
  response_status = $5,
  result_snapshot = $6
WHERE username = $1
  AND operation = $2
  AND idempotency_key = $3
  AND transaction_id IS NULL
RETURNING id, username, operation, idempotency_key, request_hash, transaction_id, response_status, result_snapshot, created_at, expires_at
`

type CompleteIdempotencyKeyParams struct {
	Username       string      `json:"username"`
	Operation      string      `json:"operation"`
	IdempotencyKey string      `json:"idempotency_key"`
	TransactionID  pgtype.UUID `json:"transaction_id"`
	ResponseStatus pgtype.Int2 `json:"response_status"`
	ResultSnapshot []byte      `json:"result_snapshot"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.Username,
		arg.Operation,
		arg.IdempotencyKey,
		arg.TransactionID,
		arg.ResponseStatus,
		arg.ResultSnapshot,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.TransactionID,
		&i.ResponseStatus,
		&i.ResultSnapshot,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countIdempotencyKeysByTransaction = `-- name: CountIdempotencyKeysByTransaction :one
SELECT count(*) FROM idempotency_keys
WHERE transaction_id = $1
`

func (q *Queries) CountIdempotencyKeysByTransaction(ctx context.Context, transactionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIdempotencyKeysByTransaction, transactionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
  username,
  operation,
  idempotency_key,
  request_hash
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (username, operation, idempotency_key) DO NOTHING
RETURNING id, username, operation, idempotency_key, request_hash, transaction_id, response_status, result_snapshot, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	Username       string `json:"username"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    []byte `json:"request_hash"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Username,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.TransactionID,
		&i.ResponseStatus,
		&i.ResultSnapshot,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKey = `-- name: DeleteExpiredIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE username = $1
  AND operation = $2
  AND idempotency_key = $3
  AND expires_at <= now()
`

type DeleteExpiredIdempotencyKeyParams struct {
	Username       string `json:"username"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKey, arg.Username, arg.Operation, arg.IdempotencyKey)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKeyForUpdate = `-- name: GetIdempotencyKeyForUpdate :one
SELECT id, username, operation, idempotency_key, request_hash, transaction_id, response_status, result_snapshot, created_at, expires_at FROM idempotency_keys
WHERE username = $1
  AND operation = $2
  AND idempotency_key = $3
FOR UPDATE
`

type GetIdempotencyKeyForUpdateParams struct {
	Username       string `json:"username"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKeyForUpdate(ctx context.Context, arg GetIdempotencyKeyForUpdateParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyForUpdate, arg.Username, arg.Operation, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.TransactionID,
		&i.ResponseStatus,
		&i.ResultSnapshot,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
