// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankingTransaction = `-- name: CreateBankingTransaction :one
INSERT INTO banking_transactions (
  id,
  reference,
  transaction_type,
  currency,
  amount,
  narration,
  initiated_by,
  reversal_of
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, reference, transaction_type, status, currency, amount, narration, initiated_by, reversal_of, created_at, posted_at, failed_at, reversed_at
`

type CreateBankingTransactionParams struct {
	ID              pgtype.UUID `json:"id"`
	Reference       string      `json:"reference"`
	TransactionType string      `json:"transaction_type"`
	Currency        string      `json:"currency"`
	Amount          int64       `json:"amount"`
	Narration       string      `json:"narration"`
	InitiatedBy     string      `json:"initiated_by"`
	ReversalOf      pgtype.UUID `json:"reversal_of"`
}

func (q *Queries) CreateBankingTransaction(ctx context.Context, arg CreateBankingTransactionParams) (BankingTransaction, error) {
	row := q.db.QueryRow(ctx, createBankingTransaction,
		arg.ID,
		arg.Reference,
		arg.TransactionType,
		arg.Currency,
		arg.Amount,
		arg.Narration,
		arg.InitiatedBy,
		arg.ReversalOf,
	)
	var i BankingTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.TransactionType,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.Narration,
		&i.InitiatedBy,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.PostedAt,
		&i.FailedAt,
		&i.ReversedAt,
	)
	return i, err
}

const createCustomerLedgerAccount = `-- name: CreateCustomerLedgerAccount :one
INSERT INTO ledger_accounts (
  customer_account_id,
  kind,
  currency
) VALUES (
  $1, 'customer', $2
)
RETURNING id, public_id, customer_account_id, code, kind, currency, created_at
`

type CreateCustomerLedgerAccountParams struct {
	CustomerAccountID pgtype.Int8 `json:"customer_account_id"`
	Currency          string      `json:"currency"`
}

func (q *Queries) CreateCustomerLedgerAccount(ctx context.Context, arg CreateCustomerLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createCustomerLedgerAccount, arg.CustomerAccountID, arg.Currency)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CustomerAccountID,
		&i.Code,
		&i.Kind,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerPosting = `-- name: CreateLedgerPosting :one
INSERT INTO ledger_postings (
  transaction_id,
  ledger_account_id,
  amount
) VALUES (
  $1, $2, $3
)
RETURNING id, transaction_id, ledger_account_id, amount, created_at
`

type CreateLedgerPostingParams struct {
	TransactionID   pgtype.UUID `json:"transaction_id"`
	LedgerAccountID int64       `json:"ledger_account_id"`
	Amount          int64       `json:"amount"`
}

func (q *Queries) CreateLedgerPosting(ctx context.Context, arg CreateLedgerPostingParams) (LedgerPosting, error) {
	row := q.db.QueryRow(ctx, createLedgerPosting, arg.TransactionID, arg.LedgerAccountID, arg.Amount)
	var i LedgerPosting
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.LedgerAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getBankingTransaction = `-- name: GetBankingTransaction :one
SELECT id, reference, transaction_type, status, currency, amount, narration, initiated_by, reversal_of, created_at, posted_at, failed_at, reversed_at FROM banking_transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBankingTransaction(ctx context.Context, id pgtype.UUID) (BankingTransaction, error) {
	row := q.db.QueryRow(ctx, getBankingTransaction, id)
	var i BankingTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.TransactionType,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.Narration,
		&i.InitiatedBy,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.PostedAt,
		&i.FailedAt,
		&i.ReversedAt,
	)
	return i, err
}

const getBankingTransactionByReference = `-- name: GetBankingTransactionByReference :one
SELECT id, reference, transaction_type, status, currency, amount, narration, initiated_by, reversal_of, created_at, posted_at, failed_at, reversed_at FROM banking_transactions
WHERE reference = $1
LIMIT 1
`

func (q *Queries) GetBankingTransactionByReference(ctx context.Context, reference string) (BankingTransaction, error) {
	row := q.db.QueryRow(ctx, getBankingTransactionByReference, reference)
	var i BankingTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.TransactionType,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.Narration,
		&i.InitiatedBy,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.PostedAt,
		&i.FailedAt,
		&i.ReversedAt,
	)
	return i, err
}

const getCustomerLedgerAccount = `-- name: GetCustomerLedgerAccount :one
SELECT id, public_id, customer_account_id, code, kind, currency, created_at FROM ledger_accounts
WHERE customer_account_id = $1
  AND kind = 'customer'
LIMIT 1
`

func (q *Queries) GetCustomerLedgerAccount(ctx context.Context, customerAccountID pgtype.Int8) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getCustomerLedgerAccount, customerAccountID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CustomerAccountID,
		&i.Code,
		&i.Kind,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerAccountBalance = `-- name: GetLedgerAccountBalance :one
SELECT coalesce(sum(amount), 0)::bigint
FROM ledger_postings
WHERE ledger_account_id = $1
`

func (q *Queries) GetLedgerAccountBalance(ctx context.Context, ledgerAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountBalance, ledgerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLedgerPostingTotal = `-- name: GetLedgerPostingTotal :one
SELECT coalesce(sum(amount), 0)::bigint
FROM ledger_postings
WHERE transaction_id = $1
`

func (q *Queries) GetLedgerPostingTotal(ctx context.Context, transactionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLedgerPostingTotal, transactionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSettlementLedgerAccount = `-- name: GetSettlementLedgerAccount :one
SELECT id, public_id, customer_account_id, code, kind, currency, created_at FROM ledger_accounts
WHERE code = 'settlement:' || $1
  AND kind = 'settlement'
LIMIT 1
`

func (q *Queries) GetSettlementLedgerAccount(ctx context.Context, currency pgtype.Text) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getSettlementLedgerAccount, currency)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CustomerAccountID,
		&i.Code,
		&i.Kind,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerPostingsByTransaction = `-- name: ListLedgerPostingsByTransaction :many
SELECT id, transaction_id, ledger_account_id, amount, created_at FROM ledger_postings
WHERE transaction_id = $1
ORDER BY id
`

func (q *Queries) ListLedgerPostingsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerPosting, error) {
	rows, err := q.db.Query(ctx, listLedgerPostingsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerPosting{}
	for rows.Next() {
		var i LedgerPosting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.LedgerAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBankingTransactionPosted = `-- name: MarkBankingTransactionPosted :one
UPDATE banking_transactions
SET
  status = 'posted',
  posted_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, reference, transaction_type, status, currency, amount, narration, initiated_by, reversal_of, created_at, posted_at, failed_at, reversed_at
`

func (q *Queries) MarkBankingTransactionPosted(ctx context.Context, id pgtype.UUID) (BankingTransaction, error) {
	row := q.db.QueryRow(ctx, markBankingTransactionPosted, id)
	var i BankingTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.TransactionType,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.Narration,
		&i.InitiatedBy,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.PostedAt,
		&i.FailedAt,
		&i.ReversedAt,
	)
	return i, err
}
