// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencyEUR Currency = "EUR"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency `json:"Currency"`
	Valid    bool     `json:"valid"` // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type Account struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Append-only audit history. Intentionally has no foreign keys so records survive entity retention cleanup.
type AuditLog struct {
	ID            int64              `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	EventType     string             `json:"event_type"`
	Actor         string             `json:"actor"`
	FromState     pgtype.Text        `json:"from_state"`
	ToState       pgtype.Text        `json:"to_state"`
	Message       pgtype.Text        `json:"message"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type EmailJob struct {
	ID                pgtype.UUID        `json:"id"`
	ParentJobID       pgtype.UUID        `json:"parent_job_id"`
	JobType           string             `json:"job_type"`
	Username          string             `json:"username"`
	Recipient         string             `json:"recipient"`
	Payload           []byte             `json:"payload"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	QueuedAt          pgtype.Timestamptz `json:"queued_at"`
	ProcessingAt      pgtype.Timestamptz `json:"processing_at"`
	LastAttemptAt     pgtype.Timestamptz `json:"last_attempt_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	DeadLetteredAt    pgtype.Timestamptz `json:"dead_lettered_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID              pgtype.UUID        `json:"id"`
	EmailJobID      pgtype.UUID        `json:"email_job_id"`
	EventType       string             `json:"event_type"`
	Payload         []byte             `json:"payload"`
	Status          string             `json:"status"`
	PublishAttempts int32              `json:"publish_attempts"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	ClaimedBy       pgtype.Text        `json:"claimed_by"`
	ClaimedUntil    pgtype.Timestamptz `json:"claimed_until"`
	LastError       pgtype.Text        `json:"last_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
