// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operational_metrics.sql

package db

import (
	"context"
)

const getFinancialOperationalMetrics = `-- name: GetFinancialOperationalMetrics :one
SELECT
  coalesce(
    extract(
      epoch FROM now() -
        min(created_at) FILTER (WHERE status IN ('pending', 'publishing'))
    ),
    0
  )::double precision AS outbox_lag_seconds,
  (
    SELECT count(*)::bigint
    FROM email_jobs
    WHERE status = 'dead_letter'
  ) AS email_dlq_size,
  (
    SELECT coalesce(sum(greatest(attempt_count - 1, 0)), 0)::bigint
    FROM email_jobs
  ) AS worker_retries,
  (
    SELECT count(*)::bigint
    FROM (
      SELECT 1
      FROM accounts AS account
      LEFT JOIN ledger_accounts AS ledger
        ON ledger.customer_account_id = account.id
       AND ledger.kind = 'customer'
      LEFT JOIN ledger_postings AS posting
        ON posting.ledger_account_id = ledger.id
      GROUP BY account.id, ledger.id
      HAVING ledger.id IS NULL
          OR account.balance <> coalesce(sum(posting.amount), 0)::bigint

      UNION ALL

      SELECT 1
      FROM banking_transactions AS transaction
      LEFT JOIN ledger_postings AS posting
        ON posting.transaction_id = transaction.id
      WHERE transaction.status IN ('posted', 'reversed')
      GROUP BY transaction.id
      HAVING count(posting.id) < 2
          OR coalesce(sum(posting.amount), 0)::bigint <> 0

      UNION ALL

      SELECT 1
      FROM banking_transactions
      WHERE reversal_of IS NOT NULL
      GROUP BY reversal_of
      HAVING count(*) > 1
    ) AS drift
  ) AS reconciliation_drift
FROM outbox_events
`

type GetFinancialOperationalMetricsRow struct {
	OutboxLagSeconds    float64 `json:"outbox_lag_seconds"`
	EmailDlqSize        int64   `json:"email_dlq_size"`
	WorkerRetries       int64   `json:"worker_retries"`
	ReconciliationDrift int64   `json:"reconciliation_drift"`
}

func (q *Queries) GetFinancialOperationalMetrics(ctx context.Context) (GetFinancialOperationalMetricsRow, error) {
	row := q.db.QueryRow(ctx, getFinancialOperationalMetrics)
	var i GetFinancialOperationalMetricsRow
	err := row.Scan(
		&i.OutboxLagSeconds,
		&i.EmailDlqSize,
		&i.WorkerRetries,
		&i.ReconciliationDrift,
	)
	return i, err
}
