// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
  SELECT id
  FROM outbox_events
  WHERE available_at <= now()
    AND (
      status = 'pending'
      OR (
        status = 'publishing'
        AND claimed_until < now()
      )
    )
  ORDER BY created_at
  FOR UPDATE SKIP LOCKED
  LIMIT $3
)
UPDATE outbox_events AS event
SET
  status = 'publishing',
  claimed_by = $1,
  claimed_until = $2,
  publish_attempts = publish_attempts + 1
FROM candidates
WHERE event.id = candidates.id
RETURNING event.id, event.email_job_id, event.event_type, event.payload, event.status, event.publish_attempts, event.available_at, event.claimed_by, event.claimed_until, event.last_error, event.created_at, event.published_at
`

type ClaimOutboxEventsParams struct {
	ClaimedBy    pgtype.Text        `json:"claimed_by"`
	ClaimedUntil pgtype.Timestamptz `json:"claimed_until"`
	BatchSize    int32              `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.ClaimedBy, arg.ClaimedUntil, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EmailJobID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.PublishAttempts,
			&i.AvailableAt,
			&i.ClaimedBy,
			&i.ClaimedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
  id,
  email_job_id,
  event_type,
  payload
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, email_job_id, event_type, payload, status, publish_attempts, available_at, claimed_by, claimed_until, last_error, created_at, published_at
`

type CreateOutboxEventParams struct {
	ID         pgtype.UUID `json:"id"`
	EmailJobID pgtype.UUID `json:"email_job_id"`
	EventType  string      `json:"event_type"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.EmailJobID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EmailJobID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.PublishAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deleteExpiredPublishedOutboxEvents = `-- name: DeleteExpiredPublishedOutboxEvents :execrows
DELETE FROM outbox_events
WHERE status = 'published'
  AND published_at < $1
`

func (q *Queries) DeleteExpiredPublishedOutboxEvents(ctx context.Context, publishedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPublishedOutboxEvents, publishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, email_job_id, event_type, payload, status, publish_attempts, available_at, claimed_by, claimed_until, last_error, created_at, published_at FROM outbox_events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EmailJobID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.PublishAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :one
UPDATE outbox_events
SET
  status = 'published',
  published_at = now(),
  claimed_by = NULL,
  claimed_until = NULL,
  last_error = NULL
WHERE id = $1
RETURNING id, email_job_id, event_type, payload, status, publish_attempts, available_at, claimed_by, claimed_until, last_error, created_at, published_at
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventPublished, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EmailJobID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.PublishAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const releaseOutboxEvent = `-- name: ReleaseOutboxEvent :one
UPDATE outbox_events
SET
  status = 'pending',
  available_at = $2,
  claimed_by = NULL,
  claimed_until = NULL,
  last_error = $3
WHERE id = $1
RETURNING id, email_job_id, event_type, payload, status, publish_attempts, available_at, claimed_by, claimed_until, last_error, created_at, published_at
`

type ReleaseOutboxEventParams struct {
	ID          pgtype.UUID        `json:"id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) ReleaseOutboxEvent(ctx context.Context, arg ReleaseOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, releaseOutboxEvent, arg.ID, arg.AvailableAt, arg.LastError)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EmailJobID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.PublishAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
