// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAccountReconciliationIssues = `-- name: ListAccountReconciliationIssues :many
SELECT
  account.public_id AS account_public_id,
  account.currency,
  account.balance AS cached_balance,
  customer_ledger.id AS customer_ledger_account_id,
  coalesce(sum(posting.amount), 0)::bigint AS ledger_balance
FROM accounts AS account
LEFT JOIN ledger_accounts AS customer_ledger
  ON customer_ledger.customer_account_id = account.id
 AND customer_ledger.kind = 'customer'
LEFT JOIN ledger_postings AS posting
  ON posting.ledger_account_id = customer_ledger.id
WHERE $1::uuid IS NULL
   OR account.public_id = $1
GROUP BY
  account.id,
  account.public_id,
  account.currency,
  account.balance,
  customer_ledger.id
HAVING customer_ledger.id IS NULL
    OR account.balance <> coalesce(sum(posting.amount), 0)::bigint
ORDER BY account.public_id
`

type ListAccountReconciliationIssuesRow struct {
	AccountPublicID         pgtype.UUID `json:"account_public_id"`
	Currency                string      `json:"currency"`
	CachedBalance           int64       `json:"cached_balance"`
	CustomerLedgerAccountID pgtype.Int8 `json:"customer_ledger_account_id"`
	LedgerBalance           int64       `json:"ledger_balance"`
}

func (q *Queries) ListAccountReconciliationIssues(ctx context.Context, accountPublicID pgtype.UUID) ([]ListAccountReconciliationIssuesRow, error) {
	rows, err := q.db.Query(ctx, listAccountReconciliationIssues, accountPublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountReconciliationIssuesRow{}
	for rows.Next() {
		var i ListAccountReconciliationIssuesRow
		if err := rows.Scan(
			&i.AccountPublicID,
			&i.Currency,
			&i.CachedBalance,
			&i.CustomerLedgerAccountID,
			&i.LedgerBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateReversalIssues = `-- name: ListDuplicateReversalIssues :many
SELECT
  original.id AS original_transaction_id,
  original.reference AS original_reference,
  count(reversal.id)::bigint AS reversal_count
FROM banking_transactions AS original
JOIN banking_transactions AS reversal
  ON reversal.reversal_of = original.id
WHERE $1::bigint IS NULL
   OR EXISTS (
     SELECT 1
     FROM ledger_postings AS scoped_posting
     JOIN ledger_accounts AS scoped_ledger
       ON scoped_ledger.id = scoped_posting.ledger_account_id
     WHERE scoped_posting.transaction_id = original.id
       AND scoped_ledger.customer_account_id = $1
   )
GROUP BY original.id, original.reference
HAVING count(reversal.id) > 1
ORDER BY original.created_at, original.id
`

type ListDuplicateReversalIssuesRow struct {
	OriginalTransactionID pgtype.UUID `json:"original_transaction_id"`
	OriginalReference     string      `json:"original_reference"`
	ReversalCount         int64       `json:"reversal_count"`
}

func (q *Queries) ListDuplicateReversalIssues(ctx context.Context, customerAccountID pgtype.Int8) ([]ListDuplicateReversalIssuesRow, error) {
	rows, err := q.db.Query(ctx, listDuplicateReversalIssues, customerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateReversalIssuesRow{}
	for rows.Next() {
		var i ListDuplicateReversalIssuesRow
		if err := rows.Scan(&i.OriginalTransactionID, &i.OriginalReference, &i.ReversalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionReconciliationIssues = `-- name: ListTransactionReconciliationIssues :many
SELECT
  transaction.id AS transaction_id,
  transaction.reference,
  transaction.status,
  count(posting.id)::bigint AS posting_count,
  coalesce(sum(posting.amount), 0)::bigint AS posting_total
FROM banking_transactions AS transaction
LEFT JOIN ledger_postings AS posting
  ON posting.transaction_id = transaction.id
WHERE transaction.status IN ('posted', 'reversed')
  AND (
    $1::bigint IS NULL
    OR EXISTS (
      SELECT 1
      FROM ledger_postings AS scoped_posting
      JOIN ledger_accounts AS scoped_ledger
        ON scoped_ledger.id = scoped_posting.ledger_account_id
      WHERE scoped_posting.transaction_id = transaction.id
        AND scoped_ledger.customer_account_id = $1
    )
  )
GROUP BY
  transaction.id,
  transaction.reference,
  transaction.status
HAVING count(posting.id) < 2
    OR coalesce(sum(posting.amount), 0)::bigint <> 0
ORDER BY transaction.created_at, transaction.id
`

type ListTransactionReconciliationIssuesRow struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	Reference     string      `json:"reference"`
	Status        string      `json:"status"`
	PostingCount  int64       `json:"posting_count"`
	PostingTotal  int64       `json:"posting_total"`
}

func (q *Queries) ListTransactionReconciliationIssues(ctx context.Context, customerAccountID pgtype.Int8) ([]ListTransactionReconciliationIssuesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionReconciliationIssues, customerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionReconciliationIssuesRow{}
	for rows.Next() {
		var i ListTransactionReconciliationIssuesRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.Reference,
			&i.Status,
			&i.PostingCount,
			&i.PostingTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
