// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  username,
  refresh_token_hash,
  refresh_token_id,
  user_agent,
  client_ip,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	Username         string             `json:"username"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	RefreshTokenID   pgtype.UUID        `json:"refresh_token_id"`
	UserAgent        string             `json:"user_agent"`
	ClientIp         string             `json:"client_ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.RefreshTokenHash,
		arg.RefreshTokenID,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshTokenID,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason FROM sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshTokenID,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason FROM sessions
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshTokenID,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason FROM sessions
WHERE username = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, username string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserAgent,
			&i.ClientIp,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshTokenHash,
			&i.RefreshTokenID,
			&i.LastRefreshedAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :many
UPDATE sessions
SET
  revoked_at = COALESCE(revoked_at, now()),
  revoked_reason = COALESCE(revoked_reason, $1)
WHERE username = $2
  AND revoked_at IS NULL
RETURNING id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason
`

type RevokeAllUserSessionsParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	Username      string      `json:"username"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, revokeAllUserSessions, arg.RevokedReason, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserAgent,
			&i.ClientIp,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RefreshTokenHash,
			&i.RefreshTokenID,
			&i.LastRefreshedAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET
  revoked_at = COALESCE(revoked_at, now()),
  revoked_reason = COALESCE(revoked_reason, $1)
WHERE id = $2
  AND revoked_at IS NULL
RETURNING id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason
`

type RevokeSessionParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.RevokedReason, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshTokenID,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const rotateSessionRefreshToken = `-- name: RotateSessionRefreshToken :one
UPDATE sessions
SET
  refresh_token_hash = $2,
  refresh_token_id = $3,
  last_refreshed_at = now()
WHERE id = $1
RETURNING id, username, user_agent, client_ip, expires_at, created_at, refresh_token_hash, refresh_token_id, last_refreshed_at, revoked_at, revoked_reason
`

type RotateSessionRefreshTokenParams struct {
	ID               pgtype.UUID `json:"id"`
	RefreshTokenHash []byte      `json:"refresh_token_hash"`
	RefreshTokenID   pgtype.UUID `json:"refresh_token_id"`
}

func (q *Queries) RotateSessionRefreshToken(ctx context.Context, arg RotateSessionRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshToken, arg.ID, arg.RefreshTokenHash, arg.RefreshTokenID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenHash,
		&i.RefreshTokenID,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}
