// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedAccountStatementBalances = `-- name: GetOwnedAccountStatementBalances :one
WITH target_ledger AS (
  SELECT ledger.id
  FROM accounts AS account
  JOIN ledger_accounts AS ledger
    ON ledger.customer_account_id = account.id
   AND ledger.kind = 'customer'
  WHERE account.public_id = $3
    AND account.owner = $4
)
SELECT
  coalesce(sum(posting.amount) FILTER (
    WHERE $1::timestamptz IS NOT NULL
      AND transaction.created_at < $1
  ), 0)::bigint AS opening_balance,
  coalesce(sum(posting.amount) FILTER (
    WHERE $2::timestamptz IS NULL
      OR transaction.created_at < $2
  ), 0)::bigint AS closing_balance
FROM target_ledger
JOIN ledger_postings AS posting
  ON posting.ledger_account_id = target_ledger.id
JOIN banking_transactions AS transaction
  ON transaction.id = posting.transaction_id
`

type GetOwnedAccountStatementBalancesParams struct {
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	AccountPublicID pgtype.UUID        `json:"account_public_id"`
	Username        string             `json:"username"`
}

type GetOwnedAccountStatementBalancesRow struct {
	OpeningBalance int64 `json:"opening_balance"`
	ClosingBalance int64 `json:"closing_balance"`
}

func (q *Queries) GetOwnedAccountStatementBalances(ctx context.Context, arg GetOwnedAccountStatementBalancesParams) (GetOwnedAccountStatementBalancesRow, error) {
	row := q.db.QueryRow(ctx, getOwnedAccountStatementBalances,
		arg.FromTime,
		arg.ToTime,
		arg.AccountPublicID,
		arg.Username,
	)
	var i GetOwnedAccountStatementBalancesRow
	err := row.Scan(&i.OpeningBalance, &i.ClosingBalance)
	return i, err
}

const getOwnedTransactionByReference = `-- name: GetOwnedTransactionByReference :one
WITH owned_activity AS (
  SELECT
    transaction.id,
    transaction.reference,
    transaction.transaction_type,
    transaction.status,
    transaction.currency,
    transaction.amount,
    transaction.narration,
    transaction.created_at,
    transaction.posted_at,
    account.public_id AS account_public_id,
    posting.amount AS signed_amount,
    CASE WHEN posting.amount > 0 THEN 'incoming' ELSE 'outgoing' END AS direction,
    coalesce(counterparty.kind, '') AS counterparty_kind,
    CASE
      WHEN counterparty.kind = 'customer' THEN counterparty.account_number
      WHEN counterparty.kind = 'settlement' THEN 'Monierave'
      ELSE ''
    END AS counterparty
  FROM banking_transactions AS transaction
  JOIN ledger_postings AS posting
    ON posting.transaction_id = transaction.id
  JOIN ledger_accounts AS ledger
    ON ledger.id = posting.ledger_account_id
  JOIN accounts AS account
    ON account.id = ledger.customer_account_id
   AND account.owner = $1
  LEFT JOIN LATERAL (
    SELECT other_ledger.kind, other_account.account_number
    FROM ledger_postings AS other_posting
    JOIN ledger_accounts AS other_ledger
      ON other_ledger.id = other_posting.ledger_account_id
    LEFT JOIN accounts AS other_account
      ON other_account.id = other_ledger.customer_account_id
    WHERE other_posting.transaction_id = transaction.id
      AND other_posting.ledger_account_id <> posting.ledger_account_id
    ORDER BY other_posting.id
    LIMIT 1
  ) AS counterparty ON true
  WHERE transaction.reference = $2
)
SELECT id, reference, transaction_type, status, currency, amount, narration, created_at, posted_at, account_public_id, signed_amount, direction, counterparty_kind, counterparty FROM owned_activity
LIMIT 1
`

type GetOwnedTransactionByReferenceParams struct {
	Username  string `json:"username"`
	Reference string `json:"reference"`
}

type GetOwnedTransactionByReferenceRow struct {
	ID               pgtype.UUID        `json:"id"`
	Reference        string             `json:"reference"`
	TransactionType  string             `json:"transaction_type"`
	Status           string             `json:"status"`
	Currency         string             `json:"currency"`
	Amount           int64              `json:"amount"`
	Narration        string             `json:"narration"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	PostedAt         pgtype.Timestamptz `json:"posted_at"`
	AccountPublicID  pgtype.UUID        `json:"account_public_id"`
	SignedAmount     int64              `json:"signed_amount"`
	Direction        string             `json:"direction"`
	CounterpartyKind string             `json:"counterparty_kind"`
	Counterparty     string             `json:"counterparty"`
}

func (q *Queries) GetOwnedTransactionByReference(ctx context.Context, arg GetOwnedTransactionByReferenceParams) (GetOwnedTransactionByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getOwnedTransactionByReference, arg.Username, arg.Reference)
	var i GetOwnedTransactionByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.TransactionType,
		&i.Status,
		&i.Currency,
		&i.Amount,
		&i.Narration,
		&i.CreatedAt,
		&i.PostedAt,
		&i.AccountPublicID,
		&i.SignedAmount,
		&i.Direction,
		&i.CounterpartyKind,
		&i.Counterparty,
	)
	return i, err
}

const listOwnedAccountTransactions = `-- name: ListOwnedAccountTransactions :many
WITH target_ledger AS (
  SELECT ledger.id
  FROM accounts AS account
  JOIN ledger_accounts AS ledger
    ON ledger.customer_account_id = account.id
   AND ledger.kind = 'customer'
  WHERE account.public_id = $2
    AND account.owner = $3
),
account_activity AS (
  SELECT
    transaction.id,
    transaction.reference,
    transaction.transaction_type,
    transaction.status,
    transaction.currency,
    transaction.amount,
    transaction.narration,
    transaction.created_at,
    transaction.posted_at,
    posting.amount AS signed_amount,
    CASE WHEN posting.amount > 0 THEN 'incoming' ELSE 'outgoing' END AS direction,
    coalesce(counterparty.kind, '') AS counterparty_kind,
    CASE
      WHEN counterparty.kind = 'customer' THEN counterparty.account_number
      WHEN counterparty.kind = 'settlement' THEN 'Monierave'
      ELSE ''
    END AS counterparty,
    sum(posting.amount) OVER (
      ORDER BY transaction.created_at, transaction.id
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )::bigint AS balance_after
  FROM target_ledger
  JOIN ledger_postings AS posting
    ON posting.ledger_account_id = target_ledger.id
  JOIN banking_transactions AS transaction
    ON transaction.id = posting.transaction_id
  LEFT JOIN LATERAL (
    SELECT other_ledger.kind, other_account.account_number
    FROM ledger_postings AS other_posting
    JOIN ledger_accounts AS other_ledger
      ON other_ledger.id = other_posting.ledger_account_id
    LEFT JOIN accounts AS other_account
      ON other_account.id = other_ledger.customer_account_id
    WHERE other_posting.transaction_id = transaction.id
      AND other_posting.ledger_account_id <> posting.ledger_account_id
    ORDER BY other_posting.id
    LIMIT 1
  ) AS counterparty ON true
),
filtered_activity AS (
  SELECT id, reference, transaction_type, status, currency, amount, narration, created_at, posted_at, signed_amount, direction, counterparty_kind, counterparty, balance_after
  FROM account_activity
  WHERE ($4::timestamptz IS NULL
      OR created_at >= $4)
    AND ($5::timestamptz IS NULL
      OR created_at < $5)
    AND ($6::varchar IS NULL
      OR transaction_type = $6)
    AND ($7::varchar IS NULL
      OR status = $7)
    AND ($8::varchar IS NULL
      OR direction = $8)
    AND (
      $9::timestamptz IS NULL
      OR (created_at, id) < (
        $9,
        $10::uuid
      )
    )
)
SELECT id, reference, transaction_type, status, currency, amount, narration, created_at, posted_at, signed_amount, direction, counterparty_kind, counterparty, balance_after
FROM filtered_activity
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListOwnedAccountTransactionsParams struct {
	PageLimit         int32              `json:"page_limit"`
	AccountPublicID   pgtype.UUID        `json:"account_public_id"`
	Username          string             `json:"username"`
	FromTime          pgtype.Timestamptz `json:"from_time"`
	ToTime            pgtype.Timestamptz `json:"to_time"`
	TransactionType   pgtype.Text        `json:"transaction_type"`
	TransactionStatus pgtype.Text        `json:"transaction_status"`
	Direction         pgtype.Text        `json:"direction"`
	CursorCreatedAt   pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID          pgtype.UUID        `json:"cursor_id"`
}

type ListOwnedAccountTransactionsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Reference        string             `json:"reference"`
	TransactionType  string             `json:"transaction_type"`
	Status           string             `json:"status"`
	Currency         string             `json:"currency"`
	Amount           int64              `json:"amount"`
	Narration        string             `json:"narration"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	PostedAt         pgtype.Timestamptz `json:"posted_at"`
	SignedAmount     int64              `json:"signed_amount"`
	Direction        string             `json:"direction"`
	CounterpartyKind string             `json:"counterparty_kind"`
	Counterparty     string             `json:"counterparty"`
	BalanceAfter     int64              `json:"balance_after"`
}

func (q *Queries) ListOwnedAccountTransactions(ctx context.Context, arg ListOwnedAccountTransactionsParams) ([]ListOwnedAccountTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedAccountTransactions,
		arg.PageLimit,
		arg.AccountPublicID,
		arg.Username,
		arg.FromTime,
		arg.ToTime,
		arg.TransactionType,
		arg.TransactionStatus,
		arg.Direction,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedAccountTransactionsRow{}
	for rows.Next() {
		var i ListOwnedAccountTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.TransactionType,
			&i.Status,
			&i.Currency,
			&i.Amount,
			&i.Narration,
			&i.CreatedAt,
			&i.PostedAt,
			&i.SignedAmount,
			&i.Direction,
			&i.CounterpartyKind,
			&i.Counterparty,
			&i.BalanceAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
