package api

import "errors"

var (
	ErrInvalidCredentials       = errors.New("invalid username or password")
	ErrUserAlreadyExists        = errors.New("user already exists")
	ErrUnauthorized             = errors.New("unauthorized")
	ErrForbidden                = errors.New("forbidden")
	ErrInternalServer           = errors.New("internal server error")
	ErrServiceUnavailable       = errors.New("service dependency unavailable")
	ErrRateLimited              = errors.New("too many requests")
	ErrInvalidToken             = errors.New("invalid token")
	ErrExpiredToken             = errors.New("expired token")
	ErrBlockedSession           = errors.New("blocked session")
	ErrInvalidSession           = errors.New("invalid user session")
	ErrSessionMismatch          = errors.New("mismatched token session")
	ErrExpiredSession           = errors.New("expired session")
	ErrCurrentPasswordRequired  = errors.New("current password is required for this security-sensitive change")
	ErrInvalidPasswordLength    = errors.New("password must be at least 8 characters and at most 72 bytes")
	ErrPasswordCompromised      = errors.New("password has appeared in a known data breach")
	ErrPasswordCheckUnavailable = errors.New("password safety check is temporarily unavailable")
	ErrInvalidFullName          = errors.New("full name must be 1-100 characters after trimming")

	ErrAccountNotFound            = errors.New("account not found")
	ErrAccountAlreadyExists       = errors.New("an account already exists for this currency")
	ErrInvalidAccountID           = errors.New("invalid account ID")
	ErrRecipientNotFound          = errors.New("recipient not found")
	ErrAccountBalanceNotZero      = errors.New("account balance must be zero before closure")
	ErrAccountAlreadyClosed       = errors.New("account is already closed")
	ErrAccountFrozen              = errors.New("source account is frozen")
	ErrAccountClosed              = errors.New("closed accounts cannot transact")
	ErrCurrencyMismatch           = errors.New("account currency mismatch")
	ErrInsufficientBalance        = errors.New("insufficient balance")
	ErrSameAccount                = errors.New("source and destination accounts must differ")
	ErrTransferFailed             = errors.New("transfer failed")
	ErrIdempotencyKeyRequired     = errors.New("Idempotency-Key header is required")
	ErrInvalidIdempotencyKey      = errors.New("Idempotency-Key must be 1-128 characters using letters, numbers, '.', '_', ':', or '-'")
	ErrIdempotencyConflict        = errors.New("Idempotency-Key was already used with a different request")
	ErrTransactionNotFound        = errors.New("transaction not found")
	ErrInvalidCursor              = errors.New("invalid transaction cursor")
	ErrInvalidDateRange           = errors.New("invalid date range")
	ErrBeneficiaryNotFound        = errors.New("beneficiary not found")
	ErrInvalidBeneficiaryID       = errors.New("invalid beneficiary ID")
	ErrBeneficiaryAlreadyExists   = errors.New("beneficiary already exists")
	ErrInvalidBeneficiaryNickname = errors.New("beneficiary nickname must be 1-50 characters after trimming")
	ErrPerTransferLimitExceeded   = errors.New("per-transfer limit exceeded")
	ErrDailyTransferLimitExceeded = errors.New("daily transfer limit exceeded")
	ErrUserNotFound               = errors.New("user not found")

	ErrUsernameAlreadyExists     = errors.New("username already exists")
	ErrEmailAlreadyExists        = errors.New("email already exists")
	ErrVerficationEmailFailed    = errors.New("failed to send verification code")
	ErrEmailVerificationRequired = errors.New("email verification is required for financial features")
	ErrRegistrationExpired       = errors.New("email verification window expired; update your email or request another verification email")
	ErrEmailAlreadyVerified      = errors.New("email is already verified")
	ErrVerificationCooldown      = errors.New("wait before requesting another verification email")
	ErrEmailAddressUndeliverable = errors.New("change your email address before requesting another verification email")
)
