// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/faelic/monierave/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination db/mock/store.go -package mockdb github.com/faelic/monierave/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/faelic/monierave/db/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddAccountBalance mocks base method.
func (m *MockStore) AddAccountBalance(ctx context.Context, arg db.AddAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountBalance", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAccountBalance indicates an expected call of AddAccountBalance.
func (mr *MockStoreMockRecorder) AddAccountBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountBalance", reflect.TypeOf((*MockStore)(nil).AddAccountBalance), ctx, arg)
}

// ClaimOutboxEvents mocks base method.
func (m *MockStore) ClaimOutboxEvents(ctx context.Context, arg db.ClaimOutboxEventsParams) ([]db.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOutboxEvents", ctx, arg)
	ret0, _ := ret[0].([]db.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOutboxEvents indicates an expected call of ClaimOutboxEvents.
func (mr *MockStoreMockRecorder) ClaimOutboxEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOutboxEvents", reflect.TypeOf((*MockStore)(nil).ClaimOutboxEvents), ctx, arg)
}

// CreateAccount mocks base method.
func (m *MockStore) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStoreMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), ctx, arg)
}

// CreateAuditLog mocks base method.
func (m *MockStore) CreateAuditLog(ctx context.Context, arg db.CreateAuditLogParams) (db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, arg)
	ret0, _ := ret[0].(db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockStoreMockRecorder) CreateAuditLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockStore)(nil).CreateAuditLog), ctx, arg)
}

// CreateEmailDeliveryEvent mocks base method.
func (m *MockStore) CreateEmailDeliveryEvent(ctx context.Context, arg db.CreateEmailDeliveryEventParams) (db.EmailDeliveryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailDeliveryEvent", ctx, arg)
	ret0, _ := ret[0].(db.EmailDeliveryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailDeliveryEvent indicates an expected call of CreateEmailDeliveryEvent.
func (mr *MockStoreMockRecorder) CreateEmailDeliveryEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailDeliveryEvent", reflect.TypeOf((*MockStore)(nil).CreateEmailDeliveryEvent), ctx, arg)
}

// CreateEmailJob mocks base method.
func (m *MockStore) CreateEmailJob(ctx context.Context, arg db.CreateEmailJobParams) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailJob", ctx, arg)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailJob indicates an expected call of CreateEmailJob.
func (mr *MockStoreMockRecorder) CreateEmailJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailJob", reflect.TypeOf((*MockStore)(nil).CreateEmailJob), ctx, arg)
}

// CreateEntry mocks base method.
func (m *MockStore) CreateEntry(ctx context.Context, arg db.CreateEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", ctx, arg)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntry indicates an expected call of CreateEntry.
func (mr *MockStoreMockRecorder) CreateEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockStore)(nil).CreateEntry), ctx, arg)
}

// CreateOutboxEvent mocks base method.
func (m *MockStore) CreateOutboxEvent(ctx context.Context, arg db.CreateOutboxEventParams) (db.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOutboxEvent", ctx, arg)
	ret0, _ := ret[0].(db.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOutboxEvent indicates an expected call of CreateOutboxEvent.
func (mr *MockStoreMockRecorder) CreateOutboxEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOutboxEvent", reflect.TypeOf((*MockStore)(nil).CreateOutboxEvent), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, arg)
}

// CreateSessionTx mocks base method.
func (m *MockStore) CreateSessionTx(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionTx", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionTx indicates an expected call of CreateSessionTx.
func (mr *MockStoreMockRecorder) CreateSessionTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionTx", reflect.TypeOf((*MockStore)(nil).CreateSessionTx), ctx, arg)
}

// CreateTransfer mocks base method.
func (m *MockStore) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, arg)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStoreMockRecorder) CreateTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStore)(nil).CreateTransfer), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(ctx context.Context, arg db.CreateUserParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), ctx, arg)
}

// DeleteAccount mocks base method.
func (m *MockStore) DeleteAccount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockStoreMockRecorder) DeleteAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), ctx, id)
}

// DeleteEntry mocks base method.
func (m *MockStore) DeleteEntry(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockStoreMockRecorder) DeleteEntry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockStore)(nil).DeleteEntry), ctx, id)
}

// DeleteExpiredPublishedOutboxEvents mocks base method.
func (m *MockStore) DeleteExpiredPublishedOutboxEvents(ctx context.Context, publishedAt pgtype.Timestamptz) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredPublishedOutboxEvents", ctx, publishedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredPublishedOutboxEvents indicates an expected call of DeleteExpiredPublishedOutboxEvents.
func (mr *MockStoreMockRecorder) DeleteExpiredPublishedOutboxEvents(ctx, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredPublishedOutboxEvents", reflect.TypeOf((*MockStore)(nil).DeleteExpiredPublishedOutboxEvents), ctx, publishedAt)
}

// DeleteExpiredSentEmailJobs mocks base method.
func (m *MockStore) DeleteExpiredSentEmailJobs(ctx context.Context, sentAt pgtype.Timestamptz) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSentEmailJobs", ctx, sentAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredSentEmailJobs indicates an expected call of DeleteExpiredSentEmailJobs.
func (mr *MockStoreMockRecorder) DeleteExpiredSentEmailJobs(ctx, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSentEmailJobs", reflect.TypeOf((*MockStore)(nil).DeleteExpiredSentEmailJobs), ctx, sentAt)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// DeleteTransfer mocks base method.
func (m *MockStore) DeleteTransfer(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransfer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransfer indicates an expected call of DeleteTransfer.
func (mr *MockStoreMockRecorder) DeleteTransfer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransfer", reflect.TypeOf((*MockStore)(nil).DeleteTransfer), ctx, id)
}

// DisableExpiredPendingUser mocks base method.
func (m *MockStore) DisableExpiredPendingUser(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableExpiredPendingUser", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableExpiredPendingUser indicates an expected call of DisableExpiredPendingUser.
func (mr *MockStoreMockRecorder) DisableExpiredPendingUser(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableExpiredPendingUser", reflect.TypeOf((*MockStore)(nil).DisableExpiredPendingUser), ctx, username)
}

// DisableExpiredPendingUsers mocks base method.
func (m *MockStore) DisableExpiredPendingUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableExpiredPendingUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableExpiredPendingUsers indicates an expected call of DisableExpiredPendingUsers.
func (mr *MockStoreMockRecorder) DisableExpiredPendingUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableExpiredPendingUsers", reflect.TypeOf((*MockStore)(nil).DisableExpiredPendingUsers), ctx)
}

// GetAccount mocks base method.
func (m *MockStore) GetAccount(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockStoreMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockStore)(nil).GetAccount), ctx, id)
}

// GetAccountForUpdate mocks base method.
func (m *MockStore) GetAccountForUpdate(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountForUpdate", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountForUpdate indicates an expected call of GetAccountForUpdate.
func (mr *MockStoreMockRecorder) GetAccountForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountForUpdate", reflect.TypeOf((*MockStore)(nil).GetAccountForUpdate), ctx, id)
}

// GetEmailDeliveryEvent mocks base method.
func (m *MockStore) GetEmailDeliveryEvent(ctx context.Context, webhookID string) (db.EmailDeliveryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailDeliveryEvent", ctx, webhookID)
	ret0, _ := ret[0].(db.EmailDeliveryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailDeliveryEvent indicates an expected call of GetEmailDeliveryEvent.
func (mr *MockStoreMockRecorder) GetEmailDeliveryEvent(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailDeliveryEvent", reflect.TypeOf((*MockStore)(nil).GetEmailDeliveryEvent), ctx, webhookID)
}

// GetEmailJob mocks base method.
func (m *MockStore) GetEmailJob(ctx context.Context, id pgtype.UUID) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailJob", ctx, id)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailJob indicates an expected call of GetEmailJob.
func (mr *MockStoreMockRecorder) GetEmailJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailJob", reflect.TypeOf((*MockStore)(nil).GetEmailJob), ctx, id)
}

// GetEmailJobByProviderMessageID mocks base method.
func (m *MockStore) GetEmailJobByProviderMessageID(ctx context.Context, providerMessageID pgtype.Text) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailJobByProviderMessageID", ctx, providerMessageID)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailJobByProviderMessageID indicates an expected call of GetEmailJobByProviderMessageID.
func (mr *MockStoreMockRecorder) GetEmailJobByProviderMessageID(ctx, providerMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailJobByProviderMessageID", reflect.TypeOf((*MockStore)(nil).GetEmailJobByProviderMessageID), ctx, providerMessageID)
}

// GetEntry mocks base method.
func (m *MockStore) GetEntry(ctx context.Context, id int64) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, id)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockStoreMockRecorder) GetEntry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockStore)(nil).GetEntry), ctx, id)
}

// GetLatestEmailJobForCurrentAddress mocks base method.
func (m *MockStore) GetLatestEmailJobForCurrentAddress(ctx context.Context, username string) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestEmailJobForCurrentAddress", ctx, username)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestEmailJobForCurrentAddress indicates an expected call of GetLatestEmailJobForCurrentAddress.
func (mr *MockStoreMockRecorder) GetLatestEmailJobForCurrentAddress(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestEmailJobForCurrentAddress", reflect.TypeOf((*MockStore)(nil).GetLatestEmailJobForCurrentAddress), ctx, username)
}

// GetOutboxEvent mocks base method.
func (m *MockStore) GetOutboxEvent(ctx context.Context, id pgtype.UUID) (db.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutboxEvent", ctx, id)
	ret0, _ := ret[0].(db.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutboxEvent indicates an expected call of GetOutboxEvent.
func (mr *MockStoreMockRecorder) GetOutboxEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutboxEvent", reflect.TypeOf((*MockStore)(nil).GetOutboxEvent), ctx, id)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(ctx context.Context, id pgtype.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), ctx, id)
}

// GetSessionForUpdate mocks base method.
func (m *MockStore) GetSessionForUpdate(ctx context.Context, id pgtype.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionForUpdate", ctx, id)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionForUpdate indicates an expected call of GetSessionForUpdate.
func (mr *MockStoreMockRecorder) GetSessionForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionForUpdate", reflect.TypeOf((*MockStore)(nil).GetSessionForUpdate), ctx, id)
}

// GetTransfer mocks base method.
func (m *MockStore) GetTransfer(ctx context.Context, id int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfer", ctx, id)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransfer indicates an expected call of GetTransfer.
func (mr *MockStoreMockRecorder) GetTransfer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransfer", reflect.TypeOf((*MockStore)(nil).GetTransfer), ctx, id)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, username)
}

// GetUserForUpdate mocks base method.
func (m *MockStore) GetUserForUpdate(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdate", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdate indicates an expected call of GetUserForUpdate.
func (mr *MockStoreMockRecorder) GetUserForUpdate(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdate", reflect.TypeOf((*MockStore)(nil).GetUserForUpdate), ctx, username)
}

// ListAccount mocks base method.
func (m *MockStore) ListAccount(ctx context.Context, arg db.ListAccountParams) ([]db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccount", ctx, arg)
	ret0, _ := ret[0].([]db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccount indicates an expected call of ListAccount.
func (mr *MockStoreMockRecorder) ListAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccount", reflect.TypeOf((*MockStore)(nil).ListAccount), ctx, arg)
}

// ListAuditLogsByJob mocks base method.
func (m *MockStore) ListAuditLogsByJob(ctx context.Context, arg db.ListAuditLogsByJobParams) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogsByJob", ctx, arg)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogsByJob indicates an expected call of ListAuditLogsByJob.
func (mr *MockStoreMockRecorder) ListAuditLogsByJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogsByJob", reflect.TypeOf((*MockStore)(nil).ListAuditLogsByJob), ctx, arg)
}

// ListDeadLetterEmailJobs mocks base method.
func (m *MockStore) ListDeadLetterEmailJobs(ctx context.Context, limit int32) ([]db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeadLetterEmailJobs", ctx, limit)
	ret0, _ := ret[0].([]db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeadLetterEmailJobs indicates an expected call of ListDeadLetterEmailJobs.
func (mr *MockStoreMockRecorder) ListDeadLetterEmailJobs(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeadLetterEmailJobs", reflect.TypeOf((*MockStore)(nil).ListDeadLetterEmailJobs), ctx, limit)
}

// ListEmailDeliveryEventsByJob mocks base method.
func (m *MockStore) ListEmailDeliveryEventsByJob(ctx context.Context, arg db.ListEmailDeliveryEventsByJobParams) ([]db.EmailDeliveryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailDeliveryEventsByJob", ctx, arg)
	ret0, _ := ret[0].([]db.EmailDeliveryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailDeliveryEventsByJob indicates an expected call of ListEmailDeliveryEventsByJob.
func (mr *MockStoreMockRecorder) ListEmailDeliveryEventsByJob(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailDeliveryEventsByJob", reflect.TypeOf((*MockStore)(nil).ListEmailDeliveryEventsByJob), ctx, arg)
}

// ListEntry mocks base method.
func (m *MockStore) ListEntry(ctx context.Context, arg db.ListEntryParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntry", ctx, arg)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntry indicates an expected call of ListEntry.
func (mr *MockStoreMockRecorder) ListEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntry", reflect.TypeOf((*MockStore)(nil).ListEntry), ctx, arg)
}

// ListRecentAuditLogs mocks base method.
func (m *MockStore) ListRecentAuditLogs(ctx context.Context, limit int32) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentAuditLogs", ctx, limit)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentAuditLogs indicates an expected call of ListRecentAuditLogs.
func (mr *MockStoreMockRecorder) ListRecentAuditLogs(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentAuditLogs", reflect.TypeOf((*MockStore)(nil).ListRecentAuditLogs), ctx, limit)
}

// ListSessions mocks base method.
func (m *MockStore) ListSessions(ctx context.Context, username string) ([]db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, username)
	ret0, _ := ret[0].([]db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockStoreMockRecorder) ListSessions(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockStore)(nil).ListSessions), ctx, username)
}

// ListTransfer mocks base method.
func (m *MockStore) ListTransfer(ctx context.Context, arg db.ListTransferParams) ([]db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfer", ctx, arg)
	ret0, _ := ret[0].([]db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfer indicates an expected call of ListTransfer.
func (mr *MockStoreMockRecorder) ListTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfer", reflect.TypeOf((*MockStore)(nil).ListTransfer), ctx, arg)
}

// MarkEmailJobDeadLetter mocks base method.
func (m *MockStore) MarkEmailJobDeadLetter(ctx context.Context, arg db.MarkEmailJobDeadLetterParams) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailJobDeadLetter", ctx, arg)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEmailJobDeadLetter indicates an expected call of MarkEmailJobDeadLetter.
func (mr *MockStoreMockRecorder) MarkEmailJobDeadLetter(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailJobDeadLetter", reflect.TypeOf((*MockStore)(nil).MarkEmailJobDeadLetter), ctx, arg)
}

// MarkEmailJobQueued mocks base method.
func (m *MockStore) MarkEmailJobQueued(ctx context.Context, id pgtype.UUID) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailJobQueued", ctx, id)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEmailJobQueued indicates an expected call of MarkEmailJobQueued.
func (mr *MockStoreMockRecorder) MarkEmailJobQueued(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailJobQueued", reflect.TypeOf((*MockStore)(nil).MarkEmailJobQueued), ctx, id)
}

// MarkEmailJobRetrying mocks base method.
func (m *MockStore) MarkEmailJobRetrying(ctx context.Context, arg db.MarkEmailJobRetryingParams) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailJobRetrying", ctx, arg)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEmailJobRetrying indicates an expected call of MarkEmailJobRetrying.
func (mr *MockStoreMockRecorder) MarkEmailJobRetrying(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailJobRetrying", reflect.TypeOf((*MockStore)(nil).MarkEmailJobRetrying), ctx, arg)
}

// MarkEmailJobSent mocks base method.
func (m *MockStore) MarkEmailJobSent(ctx context.Context, arg db.MarkEmailJobSentParams) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailJobSent", ctx, arg)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEmailJobSent indicates an expected call of MarkEmailJobSent.
func (mr *MockStoreMockRecorder) MarkEmailJobSent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailJobSent", reflect.TypeOf((*MockStore)(nil).MarkEmailJobSent), ctx, arg)
}

// MarkOutboxEventPublished mocks base method.
func (m *MockStore) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) (db.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxEventPublished", ctx, id)
	ret0, _ := ret[0].(db.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOutboxEventPublished indicates an expected call of MarkOutboxEventPublished.
func (mr *MockStoreMockRecorder) MarkOutboxEventPublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxEventPublished", reflect.TypeOf((*MockStore)(nil).MarkOutboxEventPublished), ctx, id)
}

// MarkUserEmailVerified mocks base method.
func (m *MockStore) MarkUserEmailVerified(ctx context.Context, arg db.MarkUserEmailVerifiedParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUserEmailVerified", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkUserEmailVerified indicates an expected call of MarkUserEmailVerified.
func (mr *MockStoreMockRecorder) MarkUserEmailVerified(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUserEmailVerified", reflect.TypeOf((*MockStore)(nil).MarkUserEmailVerified), ctx, arg)
}

// ProcessEmailDeliveryEventTx mocks base method.
func (m *MockStore) ProcessEmailDeliveryEventTx(ctx context.Context, arg db.ProcessEmailDeliveryEventParams) (db.ProcessEmailDeliveryEventResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessEmailDeliveryEventTx", ctx, arg)
	ret0, _ := ret[0].(db.ProcessEmailDeliveryEventResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessEmailDeliveryEventTx indicates an expected call of ProcessEmailDeliveryEventTx.
func (mr *MockStoreMockRecorder) ProcessEmailDeliveryEventTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEmailDeliveryEventTx", reflect.TypeOf((*MockStore)(nil).ProcessEmailDeliveryEventTx), ctx, arg)
}

// ReleaseOutboxEvent mocks base method.
func (m *MockStore) ReleaseOutboxEvent(ctx context.Context, arg db.ReleaseOutboxEventParams) (db.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseOutboxEvent", ctx, arg)
	ret0, _ := ret[0].(db.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseOutboxEvent indicates an expected call of ReleaseOutboxEvent.
func (mr *MockStoreMockRecorder) ReleaseOutboxEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseOutboxEvent", reflect.TypeOf((*MockStore)(nil).ReleaseOutboxEvent), ctx, arg)
}

// ReplayEmailJobTx mocks base method.
func (m *MockStore) ReplayEmailJobTx(ctx context.Context, jobID pgtype.UUID) (db.ReplayEmailJobTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayEmailJobTx", ctx, jobID)
	ret0, _ := ret[0].(db.ReplayEmailJobTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayEmailJobTx indicates an expected call of ReplayEmailJobTx.
func (mr *MockStoreMockRecorder) ReplayEmailJobTx(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayEmailJobTx", reflect.TypeOf((*MockStore)(nil).ReplayEmailJobTx), ctx, jobID)
}

// RequestEmailVerificationTx mocks base method.
func (m *MockStore) RequestEmailVerificationTx(ctx context.Context, username string) (db.RequestEmailVerificationTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailVerificationTx", ctx, username)
	ret0, _ := ret[0].(db.RequestEmailVerificationTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestEmailVerificationTx indicates an expected call of RequestEmailVerificationTx.
func (mr *MockStoreMockRecorder) RequestEmailVerificationTx(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailVerificationTx", reflect.TypeOf((*MockStore)(nil).RequestEmailVerificationTx), ctx, username)
}

// RestartUserEmailVerification mocks base method.
func (m *MockStore) RestartUserEmailVerification(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartUserEmailVerification", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestartUserEmailVerification indicates an expected call of RestartUserEmailVerification.
func (mr *MockStoreMockRecorder) RestartUserEmailVerification(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartUserEmailVerification", reflect.TypeOf((*MockStore)(nil).RestartUserEmailVerification), ctx, username)
}

// RevokeAllUserSessions mocks base method.
func (m *MockStore) RevokeAllUserSessions(ctx context.Context, arg db.RevokeAllUserSessionsParams) ([]db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessions", ctx, arg)
	ret0, _ := ret[0].([]db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllUserSessions indicates an expected call of RevokeAllUserSessions.
func (mr *MockStoreMockRecorder) RevokeAllUserSessions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessions", reflect.TypeOf((*MockStore)(nil).RevokeAllUserSessions), ctx, arg)
}

// RevokeAllUserSessionsTx mocks base method.
func (m *MockStore) RevokeAllUserSessionsTx(ctx context.Context, username, reason, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessionsTx", ctx, username, reason, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserSessionsTx indicates an expected call of RevokeAllUserSessionsTx.
func (mr *MockStoreMockRecorder) RevokeAllUserSessionsTx(ctx, username, reason, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessionsTx", reflect.TypeOf((*MockStore)(nil).RevokeAllUserSessionsTx), ctx, username, reason, eventType)
}

// RevokeSession mocks base method.
func (m *MockStore) RevokeSession(ctx context.Context, arg db.RevokeSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockStoreMockRecorder) RevokeSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockStore)(nil).RevokeSession), ctx, arg)
}

// RevokeSessionTx mocks base method.
func (m *MockStore) RevokeSessionTx(ctx context.Context, id pgtype.UUID, reason, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionTx", ctx, id, reason, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionTx indicates an expected call of RevokeSessionTx.
func (mr *MockStoreMockRecorder) RevokeSessionTx(ctx, id, reason, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionTx", reflect.TypeOf((*MockStore)(nil).RevokeSessionTx), ctx, id, reason, actor)
}

// RotateRefreshTokenTx mocks base method.
func (m *MockStore) RotateRefreshTokenTx(ctx context.Context, arg db.RotateRefreshTokenTxParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshTokenTx", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshTokenTx indicates an expected call of RotateRefreshTokenTx.
func (mr *MockStoreMockRecorder) RotateRefreshTokenTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshTokenTx", reflect.TypeOf((*MockStore)(nil).RotateRefreshTokenTx), ctx, arg)
}

// RotateSessionRefreshToken mocks base method.
func (m *MockStore) RotateSessionRefreshToken(ctx context.Context, arg db.RotateSessionRefreshTokenParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSessionRefreshToken", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSessionRefreshToken indicates an expected call of RotateSessionRefreshToken.
func (mr *MockStoreMockRecorder) RotateSessionRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSessionRefreshToken", reflect.TypeOf((*MockStore)(nil).RotateSessionRefreshToken), ctx, arg)
}

// StartEmailJobAttempt mocks base method.
func (m *MockStore) StartEmailJobAttempt(ctx context.Context, id pgtype.UUID) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartEmailJobAttempt", ctx, id)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartEmailJobAttempt indicates an expected call of StartEmailJobAttempt.
func (mr *MockStoreMockRecorder) StartEmailJobAttempt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartEmailJobAttempt", reflect.TypeOf((*MockStore)(nil).StartEmailJobAttempt), ctx, id)
}

// TransferTx mocks base method.
func (m *MockStore) TransferTx(ctx context.Context, arg db.TransferTxParams) (db.TransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTx", ctx, arg)
	ret0, _ := ret[0].(db.TransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferTx indicates an expected call of TransferTx.
func (mr *MockStoreMockRecorder) TransferTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTx", reflect.TypeOf((*MockStore)(nil).TransferTx), ctx, arg)
}

// UpdateAccount mocks base method.
func (m *MockStore) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockStoreMockRecorder) UpdateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockStore)(nil).UpdateAccount), ctx, arg)
}

// UpdateCurrentUserEmailDeliverability mocks base method.
func (m *MockStore) UpdateCurrentUserEmailDeliverability(ctx context.Context, arg db.UpdateCurrentUserEmailDeliverabilityParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentUserEmailDeliverability", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCurrentUserEmailDeliverability indicates an expected call of UpdateCurrentUserEmailDeliverability.
func (mr *MockStoreMockRecorder) UpdateCurrentUserEmailDeliverability(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentUserEmailDeliverability", reflect.TypeOf((*MockStore)(nil).UpdateCurrentUserEmailDeliverability), ctx, arg)
}

// UpdateEmailJobDelivery mocks base method.
func (m *MockStore) UpdateEmailJobDelivery(ctx context.Context, arg db.UpdateEmailJobDeliveryParams) (db.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailJobDelivery", ctx, arg)
	ret0, _ := ret[0].(db.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailJobDelivery indicates an expected call of UpdateEmailJobDelivery.
func (mr *MockStoreMockRecorder) UpdateEmailJobDelivery(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailJobDelivery", reflect.TypeOf((*MockStore)(nil).UpdateEmailJobDelivery), ctx, arg)
}

// UpdateEntry mocks base method.
func (m *MockStore) UpdateEntry(ctx context.Context, arg db.UpdateEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntry", ctx, arg)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntry indicates an expected call of UpdateEntry.
func (mr *MockStoreMockRecorder) UpdateEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockStore)(nil).UpdateEntry), ctx, arg)
}

// UpdateTransfer mocks base method.
func (m *MockStore) UpdateTransfer(ctx context.Context, arg db.UpdateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransfer", ctx, arg)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransfer indicates an expected call of UpdateTransfer.
func (mr *MockStoreMockRecorder) UpdateTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTransfer), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, arg)
}

// UpdateUserTx mocks base method.
func (m *MockStore) UpdateUserTx(ctx context.Context, arg db.UpdateUserTxParams) (db.UpdateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTx", ctx, arg)
	ret0, _ := ret[0].(db.UpdateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserTx indicates an expected call of UpdateUserTx.
func (mr *MockStoreMockRecorder) UpdateUserTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTx", reflect.TypeOf((*MockStore)(nil).UpdateUserTx), ctx, arg)
}

// ValidateSession mocks base method.
func (m *MockStore) ValidateSession(ctx context.Context, id pgtype.UUID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, id, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockStoreMockRecorder) ValidateSession(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockStore)(nil).ValidateSession), ctx, id, username)
}

// VerifyUserEmailTx mocks base method.
func (m *MockStore) VerifyUserEmailTx(ctx context.Context, arg db.VerifyUserEmailTxParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmailTx", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserEmailTx indicates an expected call of VerifyUserEmailTx.
func (mr *MockStoreMockRecorder) VerifyUserEmailTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmailTx", reflect.TypeOf((*MockStore)(nil).VerifyUserEmailTx), ctx, arg)
}
